feature/AOS2-47-open-source-dashboard-unit-test-api-service
bitovi/opensource-analytics-dashboard pull request #17
Opened 2022-11-07 21:23 UTC by vdtdev

- Pull endpoint URLs out into enum
- Update and add JSDoc comments for each method in service
- Reach 100% test coverage

2022-11-07 21:30 UTC, m-thompson-code requested changes
Looks good to me. Thanks for updating the jdocs. Only one code change suggestion. Lemme know your thoughts / if you can move to models directory

2022-11-07 21:43 UTC, m-thompson-code approved these changes
+1

2022-11-07 21:43 UTC, m-thompson-code commented
Gonna wait for @krivanek06 to approve then once we've both approved, feel free to merge when you want to @vdtdev

2022-11-08 06:11 UTC, krivanek06 approved these changes

2022-11-08 17:02 UTC, merged