feature: add custom theme
bitovi/opensource-analytics-dashboard pull request #20
Opened 2022-11-14 20:40 UTC by vdtdev

AOS2-16 [Implement Custom Theme](https://bitovi.atlassian.net/browse/AOS2-16?atlOrigin=eyJpIjoiMmRjNmYyNTJkMDFlNDhhMmJhMWZiYWVkMGM1YWM5ZjkiLCJwIjoiaiJ9)
- [ ] Add custom theme support
- [ ] Add dark mode support

2022-11-15 14:48 UTC, krivanek06 approved these changes

2022-11-16 18:09 UTC, m-thompson-code commented
tests are failing:

![Screen Shot 2022-11-16 at 10 07 45 AM](https://user-images.githubusercontent.com/9206193/202259148-69049e10-a836-4e26-a4af-17fd2ea5c1db.png)

Don't worry about all the other errors. I'll create a PR to clean everything out. Moving forward, PR's should be blocked if they throw errors during tests. I'll add a checklist to the PR template to make sure we run our tests before trying to open our PR's

2022-11-16 18:12 UTC, m-thompson-code commented
Looks like using the partial transparent border-color overlaps with the background of the div, which creates a noticeable border. I think a workaround is to set the border-color to transparent. This works since the border overlaps the background of the div:

![Screen Shot 2022-11-16 at 10 09 56 AM](https://user-images.githubusercontent.com/9206193/202259888-ec72cbb7-3c18-4161-b5b4-756568b30710.png)

![Screen Shot 2022-11-16 at 10 10 08 AM](https://user-images.githubusercontent.com/9206193/202259925-fb3aab1e-51c4-4db6-a3b0-8f1308779b89.png)

2022-11-16 18:18 UTC, m-thompson-code commented
On light mode, the border for container seems to have become lighter:

![Screen Shot 2022-11-16 at 10 16 51 AM](https://user-images.githubusercontent.com/9206193/202261013-75ff3364-dc07-401a-8971-5aecc82cfcb7.png)

![Screen Shot 2022-11-16 at 10 17 00 AM](https://user-images.githubusercontent.com/9206193/202261025-1dc5a047-0a4e-473b-957d-0116abd5d217.png)

I think the original border-color for white mode is better: rgba(0,0,0,.2)

2022-11-16 18:19 UTC, m-thompson-code requested changes
Everything looks pretty good code-wise. There's a few issues I ran into when testing:

1. tests are failing
2. light-mode container border-color should be rgba(0,0,0,.2)
3. dark-mode container border-color should be transparent

2022-11-16 18:19 UTC, m-thompson-code commented on src/theme.scss
> +			accent: $dark-accent,
:0 no warning?

2022-11-16 18:21 UTC, vdtdev commented on src/theme.scss
> +			accent: $dark-accent,
oops

2022-11-16 18:37 UTC, vdtdev commented on src/theme.scss
> +			accent: $dark-accent,
Fixed!

2022-11-16 18:41 UTC, m-thompson-code approved these changes
awesome~ now I have dark mode finally :3

2022-11-16 18:42 UTC, merged