feat: descruting application into multiple components
bitovi/opensource-analytics-dashboard pull request #4
Opened 2022-09-14 14:25 UTC by krivanek06

Destructing app.components into multiple smaller components

2022-09-15 17:55 UTC, m-thompson-code commented
There's a handful of things that will need to change for this PR, we'll sync outside of GitHub and consider a different approach

2022-09-15 17:55 UTC, m-thompson-code requested changes
Blocking for now

2022-09-19 18:51 UTC, m-thompson-code requested changes
There's a lot of moving parts in this PR. I think it would be better to handle each individual task as its own PR to make approving code changes quicker. For instance, there doesn't seem to be a whole lot of code changes needed for date-range-picker component, but there's also stuff like adding prettier and an interceptor.

2022-09-19 18:51 UTC, m-thompson-code commented on src/app/services/error-handler/error-interceptor.service.ts
> +	constructor(private matSnackBar: MatSnackBar) {}
Could we follow the pattern of using `private readonly` for our injectables? It should be common knowledge to not change the reference to an injected service, but I like the idea of marking which things should only be read and can't be overwritten

2022-09-19 18:51 UTC, m-thompson-code commented on src/app/services/npm-registry/npm-registry.service.ts
> +	providedIn: 'root',
github changes is showing this as 8 spaces for some reason. I assume this is github being weird or there actually is 8 spaces

2022-09-19 18:56 UTC, krivanek06 commented on .prettierrc
> +  "tabWidth": 2,
The majority of files are already formatted with prettier, would it make sense to remove it now?

2022-09-19 19:02 UTC, krivanek06 commented
I don't see any added benefit of discarding this PR that is almost finished. I will fix the proposed changes

2022-11-18 19:48 UTC, m-thompson-code commented
I'm going to close for now since we've made a lot of progress migrating each component in separate PRs

2022-11-18 19:48 UTC, closed without merging